CREATE TABLE IF NOT EXISTS public.backlog_analytics (
    codigo_projeto text NOT NULL,
    data_ref date NOT NULL,
    empresa text NOT NULL,
    faixa_dias text NOT NULL,
    fila text NOT NULL,
    total integer NULL
);

CREATE TABLE IF NOT EXISTS public.backlog_monitoramento (
    cidade text NULL,
    codigo_projeto text NULL,
    conta_atribuida text NULL,
    created_at timestamp with time zone NULL,
    data_criacao timestamp with time zone NULL,
    dias_em_aberto integer NULL,
    empresa text NULL,
    empresa_nome text NULL,
    estado text NULL,
    fila text NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mes_abertura text NULL,
    nome_fantasia text NULL,
    nome_projeto text NULL,
    numero_referencia text NOT NULL,
    numero_serie text NULL,
    produto_descricao text NULL,
    servico text NULL,
    situacao_equipamento text NULL,
    solucao_hardware text NULL,
    solucao_servico_software text NULL,
    status text NULL,
    status_cliente text NULL,
    tempo_atendimento_formatado text NULL,
    tempo_atendimento_horas integer NULL,
    tempo_atendimento_segundos integer NULL,
    tipo_incidente text NULL,
    tipo_problema_hardware text NULL,
    tipo_problema_servico text NULL,
    troca_tecnica text NULL
);

CREATE TABLE IF NOT EXISTS public.backlog_snapshot (
    codigo_projeto text NULL,
    created_at timestamp with time zone NULL,
    data_snapshot date NOT NULL,
    dias_em_aberto integer NULL,
    empresa text NULL,
    fila text NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    numero_referencia text NOT NULL,
    periodo text NULL,
    situacao_equipamento text NULL,
    status text NULL,
    status_cliente text NULL
);

CREATE TABLE IF NOT EXISTS public.backlog_total_diario (
    acima_30 integer NULL,
    acima_50 integer NULL,
    created_at timestamp with time zone NULL,
    data_ref date NOT NULL,
    idade_media numeric NULL,
    total_backlog integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.monitoramento_parque (
    data_gravacao date NOT NULL,
    empresa text NOT NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    total_base text NOT NULL,
    total_sem_monitoramento text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.monitoring_alert_settings (
    anomaly_enabled boolean NOT NULL,
    anomaly_moving_avg_days integer NOT NULL,
    anomaly_stddev_multiplier integer NOT NULL,
    auto_resolve_consecutive_readings integer NOT NULL,
    auto_resolve_enabled boolean NOT NULL,
    created_at timestamp with time zone  DEFAULT now(),
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    tipo_monitoramento text NOT NULL,
    trend_consecutive_periods integer NOT NULL,
    trend_enabled boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.monitoring_alerts (
    alert_type text NOT NULL,
    comentario_tratamento text NULL,
    contexto jsonb NULL,
    created_at timestamp with time zone  DEFAULT now(),
    detected_at text NOT NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    identificador_item text NOT NULL,
    percentual_atual numeric NOT NULL,
    severity text NOT NULL,
    tipo_monitoramento text NOT NULL,
    tratado boolean NOT NULL,
    tratado_em text NULL,
    tratado_por bigint NULL
);

CREATE TABLE IF NOT EXISTS public.permissions (
    description text NULL,
    key text NOT NULL,
    module text NOT NULL,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.presentation_settings (
    companies_per_page integer NOT NULL,
    created_at timestamp with time zone  DEFAULT now(),
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    ignore_green boolean NOT NULL,
    ignore_red boolean NOT NULL,
    ignore_yellow boolean NOT NULL,
    interval_seconds integer NOT NULL,
    max_percentage integer NULL,
    min_percentage integer NULL,
    monitoring_type text NOT NULL,
    theme_danger text NULL,
    theme_success text NULL,
    theme_warning text NULL,
    threshold_atencao integer NULL,
    threshold_attention integer NULL,
    threshold_critical integer NULL,
    threshold_excelente integer NULL,
    threshold_excellent integer NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.role_audit_log (
    action text NOT NULL,
    changed_at text NULL,
    changed_by integer NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    new_values jsonb NULL,
    old_values jsonb NULL,
    role_id bigint NULL
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    created_at timestamp with time zone NULL,
    enabled boolean NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    permission_key text NULL,
    role_id bigint NULL,
    updated_at timestamp with time zone NULL
);

CREATE TABLE IF NOT EXISTS public.roles (
    description text NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    is_active boolean NULL,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sessions (
    created_at timestamp with time zone NULL,
    expires_at text NOT NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ip_address text NULL,
    revoked boolean NULL,
    session_token text NOT NULL,
    user_agent text NULL,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sla_detalhado_rn (
    categoria_perda_sla text NULL,
    cidade text NULL,
    conta_atribuida text NULL,
    created_at timestamp with time zone  DEFAULT now(),
    data_criacao timestamp with time zone NULL,
    data_fechamento timestamp with time zone NULL,
    dentro integer NOT NULL,
    dentro_fora text NOT NULL,
    dia integer NULL,
    divisao_perda_sla text NULL,
    empresa text NULL,
    fila text NULL,
    fora integer NOT NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    mes text NULL,
    motivo_perda_sla text NULL,
    nome_projeto text NULL,
    numero_referencia text NULL,
    numero_serie text NULL,
    observacao_perda_sla text NULL,
    produto_descricao text NULL,
    qtde_pausa integer NOT NULL,
    sla_contratual text NULL,
    sla_perdido text NULL,
    sla_solucao integer NULL,
    solucao_hardware text NULL,
    status text NULL,
    tipo_incidente text NULL,
    tipo_problema_hardware text NULL,
    tipo_sla text NULL,
    uf text NULL
);

CREATE TABLE IF NOT EXISTS public.sla_fila_rn (
    created_at timestamp with time zone NULL,
    dentro integer NOT NULL,
    fora integer NOT NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_fila text NOT NULL,
    percentual numeric NOT NULL,
    total integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sla_metas (
    ativo boolean NOT NULL,
    created_at timestamp with time zone NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    identificador text NOT NULL,
    meta_atencao integer NULL,
    meta_excelente integer NULL,
    tipo text NOT NULL,
    valid_from text NOT NULL,
    valid_to text NULL
);

CREATE TABLE IF NOT EXISTS public.sla_metas_log (
    alterado_em text NOT NULL,
    alterado_por text NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    identificador text NOT NULL,
    meta_atencao_new integer NULL,
    meta_atencao_old integer NULL,
    meta_excelente_new integer NULL,
    meta_excelente_old integer NULL,
    meta_id text NOT NULL,
    tipo text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sla_projetos_rn (
    created_at timestamp with time zone NULL,
    created_at_hour text NULL,
    dentro integer NOT NULL,
    fora integer NOT NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_projeto text NOT NULL,
    percentual numeric NOT NULL,
    total integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.smtp_settings (
    created_at timestamp with time zone  DEFAULT now(),
    enabled boolean NOT NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    smtp_from_email text NOT NULL,
    smtp_from_name text NOT NULL,
    smtp_host text NOT NULL,
    smtp_password text NOT NULL,
    smtp_port integer NOT NULL,
    smtp_secure boolean NOT NULL,
    smtp_user text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    created_at timestamp with time zone NULL,
    department text NULL,
    email text NOT NULL,
    full_name text NOT NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    is_active boolean NULL,
    password_hash text NOT NULL,
    role_id bigint NOT NULL,
    updated_at timestamp with time zone NULL,
    username text NOT NULL
);