import re
import json

types_file = r"c:\Users\felipe.goncalves\Documents\Projeto MPS\Monitoramento\felipe-s-personal-space\src\integrations\supabase\types.ts"

with open(types_file, "r", encoding="utf-8") as f:
    content = f.read()

# Very basic parsing for Tables
# We look for "Tables: {" and then match each table block
match = re.search(r"Tables: \{(.+?)\n    [A-Z][a-z]+:", content, re.DOTALL)
if not match:
    # Try alternate regex or just string splitting
    start_idx = content.find("Tables: {")
    end_idx = content.find("Views: {")
    if end_idx == -1:
        end_idx = content.find("Functions: {")
    if end_idx == -1:
         end_idx = content.find("Enums: {")
    tables_content = content[start_idx:end_idx]
else:
    tables_content = match.group(1)

# print(tables_content[:500])

tables = {}
current_table = None
in_row = False

for line in tables_content.split('\n'):
    line = line.replace('\r', '')
    if re.match(r'^\s{6}([a-zA-Z0-9_]+): \{', line):
        table_name = re.match(r'^\s{6}([a-zA-Z0-9_]+): \{', line).group(1)
        current_table = table_name
        tables[current_table] = []
    elif current_table and re.match(r'^\s{8}Row: \{', line):
        in_row = True
    elif current_table and in_row and re.match(r'^\s{8}\}', line):
        in_row = False
        current_table = None
    elif current_table and in_row:
        m = re.match(r'^\s{10}([a-zA-Z0-9_]+)\??:\s*(.+)$', line)
        if m:
            col_name = m.group(1)
            col_type_ts = m.group(2)
            
            # Remove trailing commas
            if col_type_ts.endswith(','):
                col_type_ts = col_type_ts[:-1]
                
            nullable = "null" in col_type_ts
            col_type_ts = col_type_ts.replace(' | null', '').strip()
            
            # Map TS type to SQL type
            sql_type = "text"
            if col_type_ts == "string":
                if "created_at" in col_name or "updated_at" in col_name or "data" in col_name or "time" in col_name:
                    if col_name in ['created_at', 'updated_at', 'deleted_at', 'data_criacao', 'data_fechamento', 'detected_at', 'tratado_em', 'valid_from', 'valid_to', 'alterado_em', 'expires_at', 'changed_at']:
                         sql_type = "timestamp with time zone"
                    elif col_name in ['data_ref', 'data_snapshot', 'data_gravacao', 'mes_abertura', 'mes']: 
                         sql_type = "date"
                    else:
                        sql_type = "text"
                else:
                    if col_name == "id":
                        sql_type = "uuid"
                    else:
                        sql_type = "text"
            elif col_type_ts == "number":
                if col_name == "id" or col_name.endswith("_id") or col_name.endswith("por"):
                    sql_type = "bigint"
                elif "percentual" in col_name or "idade" in col_name:
                    sql_type = "numeric"
                else:
                    sql_type = "integer"
            elif col_type_ts == "boolean":
                sql_type = "boolean"
            elif col_type_ts == "Json":
                sql_type = "jsonb"
            elif col_type_ts == "string[]":
                sql_type = "text[]"
                
            tables[current_table].append({
                "name": col_name,
                "type": sql_type,
                "nullable": nullable
            })


sql_statements = []
for table, cols in tables.items():
    stmt = f"CREATE TABLE IF NOT EXISTS public.{table} (\n"
    col_defs = []
    
    # Check if we have an ID column
    has_id = any(c["name"] == "id" for c in cols)
    
    for c in cols:
        nullable_str = "NULL" if c["nullable"] else "NOT NULL"
        is_pk = ""
        
        if c["name"] == "id":
            if c["type"] == "uuid":
                is_pk = " PRIMARY KEY DEFAULT gen_random_uuid()"
            elif c["type"] in ["integer", "bigint"]:
                is_pk = " PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"
            nullable_str = "" # PK implies NOT NULL
            
        default_str = ""
        if "created_at" in c["name"] and not c["nullable"]:
            default_str = " DEFAULT now()"
            nullable_str = ""
            
        col_defs.append(f"    {c['name']} {c['type']} {nullable_str}{is_pk}{default_str}")
        
    stmt += ",\n".join(col_defs)
    stmt += "\n);"
    sql_statements.append(stmt)

final_sql = "\n\n".join(sql_statements)
with open("c:/Users/felipe.goncalves/Documents/Projeto MPS/Monitoramento/felipe-s-personal-space/deploy_schema_gerado.sql", "w", encoding="utf-8") as f:
    f.write(final_sql)

print(f"Generated {len(tables)} tables to deploy_schema_gerado.sql")
