-- ========================================================
-- SUPABASE FULL DEPLOYMENT SCRIPT (AUTO-GENERATED)
-- ========================================================

-- 1. TABLES GENERATED FROM TYPES.TS

CREATE TABLE IF NOT EXISTS public.backlog_analytics (
    codigo_projeto text NOT NULL,
    data_ref date NOT NULL,
    empresa text NOT NULL,
    faixa_dias text NOT NULL,
    fila text NOT NULL,
    total integer NULL
);

CREATE TABLE IF NOT EXISTS public.backlog_monitoramento (
    cidade text NULL,
    codigo_projeto text NULL,
    conta_atribuida text NULL,
    created_at timestamp with time zone NULL,
    data_criacao timestamp with time zone NULL,
    dias_em_aberto integer NULL,
    empresa text NULL,
    empresa_nome text NULL,
    estado text NULL,
    fila text NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mes_abertura text NULL,
    nome_fantasia text NULL,
    nome_projeto text NULL,
    numero_referencia text NOT NULL,
    numero_serie text NULL,
    produto_descricao text NULL,
    servico text NULL,
    situacao_equipamento text NULL,
    solucao_hardware text NULL,
    solucao_servico_software text NULL,
    status text NULL,
    status_cliente text NULL,
    tempo_atendimento_formatado text NULL,
    tempo_atendimento_horas integer NULL,
    tempo_atendimento_segundos integer NULL,
    tipo_incidente text NULL,
    tipo_problema_hardware text NULL,
    tipo_problema_servico text NULL,
    troca_tecnica text NULL
);

CREATE TABLE IF NOT EXISTS public.backlog_snapshot (
    codigo_projeto text NULL,
    created_at timestamp with time zone NULL,
    data_snapshot date NOT NULL,
    dias_em_aberto integer NULL,
    empresa text NULL,
    fila text NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    numero_referencia text NOT NULL,
    periodo text NULL,
    situacao_equipamento text NULL,
    status text NULL,
    status_cliente text NULL
);

CREATE TABLE IF NOT EXISTS public.backlog_total_diario (
    acima_30 integer NULL,
    acima_50 integer NULL,
    created_at timestamp with time zone NULL,
    data_ref date NOT NULL,
    idade_media numeric NULL,
    total_backlog integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.monitoramento_parque (
    data_gravacao date NOT NULL,
    empresa text NOT NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    total_base text NOT NULL,
    total_sem_monitoramento text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.monitoring_alert_settings (
    anomaly_enabled boolean NOT NULL,
    anomaly_moving_avg_days integer NOT NULL,
    anomaly_stddev_multiplier integer NOT NULL,
    auto_resolve_consecutive_readings integer NOT NULL,
    auto_resolve_enabled boolean NOT NULL,
    created_at timestamp with time zone  DEFAULT now(),
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    tipo_monitoramento text NOT NULL,
    trend_consecutive_periods integer NOT NULL,
    trend_enabled boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.monitoring_alerts (
    alert_type text NOT NULL,
    comentario_tratamento text NULL,
    contexto jsonb NULL,
    created_at timestamp with time zone  DEFAULT now(),
    detected_at text NOT NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    identificador_item text NOT NULL,
    percentual_atual numeric NOT NULL,
    severity text NOT NULL,
    tipo_monitoramento text NOT NULL,
    tratado boolean NOT NULL,
    tratado_em text NULL,
    tratado_por bigint NULL
);

CREATE TABLE IF NOT EXISTS public.permissions (
    description text NULL,
    key text NOT NULL,
    module text NOT NULL,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.presentation_settings (
    companies_per_page integer NOT NULL,
    created_at timestamp with time zone  DEFAULT now(),
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    ignore_green boolean NOT NULL,
    ignore_red boolean NOT NULL,
    ignore_yellow boolean NOT NULL,
    interval_seconds integer NOT NULL,
    max_percentage integer NULL,
    min_percentage integer NULL,
    monitoring_type text NOT NULL,
    theme_danger text NULL,
    theme_success text NULL,
    theme_warning text NULL,
    threshold_atencao integer NULL,
    threshold_attention integer NULL,
    threshold_critical integer NULL,
    threshold_excelente integer NULL,
    threshold_excellent integer NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.role_audit_log (
    action text NOT NULL,
    changed_at text NULL,
    changed_by integer NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    new_values jsonb NULL,
    old_values jsonb NULL,
    role_id bigint NULL
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    created_at timestamp with time zone NULL,
    enabled boolean NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    permission_key text NULL,
    role_id bigint NULL,
    updated_at timestamp with time zone NULL
);

CREATE TABLE IF NOT EXISTS public.roles (
    description text NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    is_active boolean NULL,
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sessions (
    created_at timestamp with time zone NULL,
    expires_at text NOT NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ip_address text NULL,
    revoked boolean NULL,
    session_token text NOT NULL,
    user_agent text NULL,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sla_detalhado_rn (
    categoria_perda_sla text NULL,
    cidade text NULL,
    conta_atribuida text NULL,
    created_at timestamp with time zone  DEFAULT now(),
    data_criacao timestamp with time zone NULL,
    data_fechamento timestamp with time zone NULL,
    dentro integer NOT NULL,
    dentro_fora text NOT NULL,
    dia integer NULL,
    divisao_perda_sla text NULL,
    empresa text NULL,
    fila text NULL,
    fora integer NOT NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    mes text NULL,
    motivo_perda_sla text NULL,
    nome_projeto text NULL,
    numero_referencia text NULL,
    numero_serie text NULL,
    observacao_perda_sla text NULL,
    produto_descricao text NULL,
    qtde_pausa integer NOT NULL,
    sla_contratual text NULL,
    sla_perdido text NULL,
    sla_solucao integer NULL,
    solucao_hardware text NULL,
    status text NULL,
    tipo_incidente text NULL,
    tipo_problema_hardware text NULL,
    tipo_sla text NULL,
    uf text NULL
);

CREATE TABLE IF NOT EXISTS public.sla_fila_rn (
    created_at timestamp with time zone NULL,
    dentro integer NOT NULL,
    fora integer NOT NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_fila text NOT NULL,
    percentual numeric NOT NULL,
    total integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sla_metas (
    ativo boolean NOT NULL,
    created_at timestamp with time zone NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    identificador text NOT NULL,
    meta_atencao integer NULL,
    meta_excelente integer NULL,
    tipo text NOT NULL,
    valid_from text NOT NULL,
    valid_to text NULL
);

CREATE TABLE IF NOT EXISTS public.sla_metas_log (
    alterado_em text NOT NULL,
    alterado_por text NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    identificador text NOT NULL,
    meta_atencao_new integer NULL,
    meta_atencao_old integer NULL,
    meta_excelente_new integer NULL,
    meta_excelente_old integer NULL,
    meta_id text NOT NULL,
    tipo text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sla_projetos_rn (
    created_at timestamp with time zone NULL,
    created_at_hour text NULL,
    dentro integer NOT NULL,
    fora integer NOT NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_projeto text NOT NULL,
    percentual numeric NOT NULL,
    total integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.smtp_settings (
    created_at timestamp with time zone  DEFAULT now(),
    enabled boolean NOT NULL,
    id uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
    smtp_from_email text NOT NULL,
    smtp_from_name text NOT NULL,
    smtp_host text NOT NULL,
    smtp_password text NOT NULL,
    smtp_port integer NOT NULL,
    smtp_secure boolean NOT NULL,
    smtp_user text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    created_at timestamp with time zone NULL,
    department text NULL,
    email text NOT NULL,
    full_name text NOT NULL,
    id bigint  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    is_active boolean NULL,
    password_hash text NOT NULL,
    role_id bigint NOT NULL,
    updated_at timestamp with time zone NULL,
    username text NOT NULL
);

-- 2. CONSTRAINTS AND FOREIGN KEYS

--
-- Primary Keys & Constraints for tables that didn't have 'id'
--
ALTER TABLE public.permissions ADD PRIMARY KEY (key);

--
-- Foreign Keys
--
ALTER TABLE public.monitoring_alerts ADD CONSTRAINT monitoring_alerts_tratado_por_fkey FOREIGN KEY (tratado_por) REFERENCES public.users(id);
ALTER TABLE public.role_audit_log ADD CONSTRAINT role_audit_log_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id);
ALTER TABLE public.role_audit_log ADD CONSTRAINT role_audit_log_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_permission_key_fkey FOREIGN KEY (permission_key) REFERENCES public.permissions(key);
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.users ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id);


-- 3. RPCs, RLS, AND TRIGGERS FROM MANUAL MIGRATIONS
-- ==========================================
-- Migration: 20240212_permissions_and_rpc.sql
-- ==========================================

-- Insert Permissions
INSERT INTO permissions (key, name, description, module) VALUES
('VIEW_MPS', 'Visualizar MPS', 'Permite visualizar dados de MPS', 'MONITORAMENTO'),
('VIEW_SLA_FILA', 'Visualizar SLA Fila', 'Permite visualizar SLA por Fila', 'MONITORAMENTO'),
('VIEW_SLA_PROJETO', 'Visualizar SLA Projeto', 'Permite visualizar SLA por Projeto', 'MONITORAMENTO'),
('VIEW_SLA_ANALYSIS', 'Visualizar Análise de SLA', 'Permite visualizar análise de SLA', 'ANÁLISE SLA'),
('EXPORT_SLA_ANALYSIS', 'Exportar dados de SLA', 'Permite exportar dados de SLA', 'ANÁLISE SLA'),
('VIEW_REPORTS', 'Visualizar Relatórios', 'Permite visualizar relatórios', 'RELATÓRIOS'),
('EXPORT_REPORTS', 'Exportar Relatórios', 'Permite exportar relatórios', 'RELATÓRIOS'),
('CONFIG_ALERTS', 'Configurar Alertas', 'Permite configurar alertas', 'CONFIGURAÇÕES'),
('CONFIG_PRESENTATION', 'Configurar Apresentação', 'Permite configurar modo apresentação', 'CONFIGURAÇÕES'),
('CONFIG_SMTP', 'Configurar SMTP', 'Permite configurar SMTP', 'CONFIGURAÇÕES'),
('CONFIG_METAS', 'Configurar Metas', 'Permite configurar metas de SLA', 'CONFIGURAÇÕES'),
('CONFIG_ROLES', 'Gerenciar Perfis', 'Permite gerenciar perfis de acesso', 'CONFIGURAÇÕES')
ON CONFLICT (key) DO NOTHING;

-- Create RPC for Daily SLA Evolution
CREATE OR REPLACE FUNCTION get_sla_daily_evolution(p_month date DEFAULT date_trunc('month', now()))
RETURNS TABLE (
  dia date,
  dentro bigint,
  fora bigint,
  percentual numeric
) AS $$
BEGIN
  RETURN QUERY
  WITH dias AS (
    SELECT generate_series(
      date_trunc('month', p_month),
      date_trunc('month', p_month) + interval '1 month' - interval '1 day',
      interval '1 day'
    )::date AS dia
  ),
  dados AS (
    SELECT
      date_trunc('day', data_criacao)::date AS dia,
      SUM(sla_detalhado_rn.dentro) AS dentro,
      SUM(sla_detalhado_rn.fora) AS fora
    FROM public.sla_detalhado_rn
    WHERE date_trunc('month', data_criacao) = date_trunc('month', p_month)
    GROUP BY 1
  )
  SELECT
    d.dia,
    COALESCE(dados.dentro, 0) AS dentro,
    COALESCE(dados.fora, 0) AS fora,
    CASE
      WHEN COALESCE(dados.dentro,0) + COALESCE(dados.fora,0) > 0
      THEN ROUND(
        (dados.dentro::numeric /
        (dados.dentro + dados.fora)) * 100
      ,2)
      ELSE NULL
    END AS percentual
  FROM dias d
  LEFT JOIN dados ON dados.dia = d.dia
  ORDER BY d.dia;
END;
$$ LANGUAGE plpgsql;


-- ==========================================
-- Migration: 20260130122322_8e7f21d8-7421-4492-95cd-22d4091332e7.sql
-- ==========================================

-- Create function to update timestamps if not exists
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Create presentation_settings table for storing presentation mode configuration

-- Insert default configuration
INSERT INTO public.presentation_settings (companies_per_page, interval_seconds) 
VALUES (4, 10);

-- Enable RLS
ALTER TABLE public.presentation_settings ENABLE ROW LEVEL SECURITY;

-- Create policy for reading settings (anyone can read)
CREATE POLICY "Anyone can view presentation settings" 
ON public.presentation_settings 
FOR SELECT 
USING (true);

-- Create policy for updating settings
CREATE POLICY "Anyone can update presentation settings" 
ON public.presentation_settings 
FOR UPDATE 
USING (true);

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_presentation_settings_updated_at
BEFORE UPDATE ON public.presentation_settings
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- ==========================================
-- Migration: 20260130150715_7a9ada24-ac15-495f-97be-51544c72fc40.sql
-- ==========================================

-- Add monitoring_type column to presentation_settings
ALTER TABLE public.presentation_settings 
ADD COLUMN monitoring_type text NOT NULL DEFAULT 'mps';

-- Create unique constraint for monitoring_type
ALTER TABLE public.presentation_settings 
ADD CONSTRAINT presentation_settings_monitoring_type_unique UNIQUE (monitoring_type);

-- Update existing row to be for 'mps'
UPDATE public.presentation_settings SET monitoring_type = 'mps' WHERE monitoring_type = 'mps';

-- Insert default settings for sla_fila and sla_projetos
INSERT INTO public.presentation_settings (monitoring_type, companies_per_page, interval_seconds, min_percentage, max_percentage, ignore_green, ignore_yellow, ignore_red)
VALUES 
  ('sla_fila', 4, 10, NULL, NULL, false, false, false),
  ('sla_projetos', 4, 10, NULL, NULL, false, false, false)
ON CONFLICT (monitoring_type) DO NOTHING;

-- ==========================================
-- Migration: 20260210150703_2a5048cd-774f-4227-8b74-529e6dd52b3c.sql
-- ==========================================


-- Create index for performance on sla_projetos_rn
CREATE INDEX IF NOT EXISTS idx_sla_projetos_rn_created_at_desc ON sla_projetos_rn (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sla_fila_rn_created_at_desc ON sla_fila_rn (created_at DESC);

-- Function to get latest N records per item efficiently
CREATE OR REPLACE FUNCTION get_latest_sla_records(
  p_type TEXT,
  p_records_per_item INT DEFAULT 2
)
RETURNS TABLE (
  id INT,
  nome TEXT,
  dentro INT,
  fora INT,
  percentual NUMERIC,
  total INT,
  created_at TIMESTAMPTZ,
  row_num BIGINT
)
LANGUAGE SQL
STABLE
AS $$
  SELECT sub.id, sub.nome, sub.dentro, sub.fora, sub.percentual, sub.total, sub.created_at, sub.rn
  FROM (
    SELECT 
      f.id,
      f.nome_fila AS nome,
      f.dentro,
      f.fora,
      f.percentual,
      f.total,
      f.created_at,
      ROW_NUMBER() OVER (PARTITION BY f.nome_fila ORDER BY f.created_at DESC) AS rn
    FROM sla_fila_rn f
    WHERE p_type = 'fila'
    UNION ALL
    SELECT 
      p.id,
      p.nome_projeto AS nome,
      p.dentro,
      p.fora,
      p.percentual,
      p.total,
      p.created_at,
      ROW_NUMBER() OVER (PARTITION BY p.nome_projeto ORDER BY p.created_at DESC) AS rn
    FROM sla_projetos_rn p
    WHERE p_type = 'projetos'
  ) sub
  WHERE sub.rn <= p_records_per_item
  ORDER BY sub.nome, sub.rn;
$$;


-- ==========================================
-- Migration: 20260210170233_43077fa8-d734-4ba7-b5b4-fb99e54606e8.sql
-- ==========================================


-- RPC to get history data aggregated by day or hour (latest per period)
CREATE OR REPLACE FUNCTION get_sla_history(
  p_type TEXT,
  p_identifier TEXT,
  p_granularity TEXT DEFAULT 'daily',
  p_days INT DEFAULT 15
)
RETURNS TABLE (
  period_key TEXT,
  display_date TEXT,
  dentro BIGINT,
  fora BIGINT,
  percentual NUMERIC,
  recorded_at TIMESTAMPTZ
)
LANGUAGE SQL
STABLE
AS $$
  WITH source AS (
    SELECT 
      f.dentro,
      f.fora,
      f.created_at,
      CASE 
        WHEN p_granularity = 'daily' THEN to_char(f.created_at, 'YYYY-MM-DD')
        ELSE to_char(f.created_at, 'YYYY-MM-DD HH24')
      END AS pkey,
      CASE 
        WHEN p_granularity = 'daily' THEN to_char(f.created_at, 'DD/MM')
        ELSE to_char(f.created_at, 'DD/MM HH24') || 'h'
      END AS ddate,
      ROW_NUMBER() OVER (
        PARTITION BY 
          CASE 
            WHEN p_granularity = 'daily' THEN to_char(f.created_at, 'YYYY-MM-DD')
            ELSE to_char(f.created_at, 'YYYY-MM-DD HH24')
          END
        ORDER BY f.created_at DESC
      ) AS rn
    FROM sla_fila_rn f
    WHERE p_type = 'sla_fila'
      AND f.nome_fila = p_identifier
      AND f.created_at >= now() - (p_days || ' days')::interval
    
    UNION ALL
    
    SELECT 
      p.dentro,
      p.fora,
      p.created_at,
      CASE 
        WHEN p_granularity = 'daily' THEN to_char(p.created_at, 'YYYY-MM-DD')
        ELSE to_char(p.created_at, 'YYYY-MM-DD HH24')
      END AS pkey,
      CASE 
        WHEN p_granularity = 'daily' THEN to_char(p.created_at, 'DD/MM')
        ELSE to_char(p.created_at, 'DD/MM HH24') || 'h'
      END AS ddate,
      ROW_NUMBER() OVER (
        PARTITION BY 
          CASE 
            WHEN p_granularity = 'daily' THEN to_char(p.created_at, 'YYYY-MM-DD')
            ELSE to_char(p.created_at, 'YYYY-MM-DD HH24')
          END
        ORDER BY p.created_at DESC
      ) AS rn
    FROM sla_projetos_rn p
    WHERE p_type = 'sla_projetos'
      AND p.nome_projeto = p_identifier
      AND p.created_at >= now() - (p_days || ' days')::interval
  )
  SELECT 
    s.pkey,
    s.ddate,
    s.dentro,
    s.fora,
    CASE WHEN (s.dentro + s.fora) > 0 
      THEN ROUND((s.dentro::numeric / (s.dentro + s.fora)::numeric) * 100, 2)
      ELSE 100
    END,
    s.created_at
  FROM source s
  WHERE s.rn = 1
  ORDER BY s.pkey ASC;
$$;


-- ==========================================
-- 4. DEFAULT SYSTEM DATA (ROLES & USERS)
-- ==========================================

-- Insert Default Role: ADM
INSERT INTO public.roles (name, is_active, description) 
VALUES ('ADM', true, 'Administrador do Sistema');

-- Link ADM to all permissions
INSERT INTO public.role_permissions (permission_key, role_id, enabled, created_at, updated_at)
SELECT 
    p.key, 
    r.id, 
    true, 
    now(), 
    now()
FROM public.permissions p
CROSS JOIN public.roles r
WHERE r.name = 'ADM';

-- Insert Admin User with bcrypt hash for 'admin123'
INSERT INTO public.users (email, full_name, username, password_hash, role_id, is_active, department, created_at, updated_at)
SELECT
    'admin@admin.com',
    'Administrador',
    'admin',
    '$2b$10$3Qp37G/9Mlm9ZSOfMQc4VOoyRUZlcV96PwEfwEemL0zZ5htrE/3n2',
    id,
    true,
    'TI',
    now(),
    now()
FROM public.roles 
WHERE name = 'ADM'
LIMIT 1;

