// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qromvrzqktrfexbnaoem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyb212cnpxa3RyZmV4Ym5hb2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MDU1NTQsImV4cCI6MjA4NTI4MTU1NH0.ipfWhsP7QJSCGBpbILyQyfj2KmRvrvpnB90ISPO7gug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});